# Form implementation generated from reading ui file 'VentanaCreada.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 681, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.texto = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.texto.setObjectName("texto")
        self.verticalLayout.addWidget(self.texto)
        self.campo = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.campo.setObjectName("campo")
        self.verticalLayout.addWidget(self.campo)
        self.boton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.boton.setObjectName("boton")
        self.verticalLayout.addWidget(self.boton)
        self.boton_no = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.boton_no.setObjectName("boton_no")
        self.verticalLayout.addWidget(self.boton_no)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.texto.setText(_translate("MainWindow", "TextLabel"))
        self.boton.setText(_translate("MainWindow", "PushButton"))
        self.boton_no.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
